// <auto-generated />
namespace The_Journal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Sortingoutmaincarer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sortingoutmaincarer));
        
        string IMigrationMetadata.Id
        {
            get { return "201511301212083_Sorting out main carer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
